sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucket-name: sky-take-out-zephyrwn
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx4a87d772be6ba582
    secret: 741d1328b072e74011764fbace73a6ee
  shop:
    address: 北京市海淀区上地十街10号
  baidu:
    ak: nyOuuki9QROyopIlvHvQSPLc251TBdah
